spring.application.name=RateLimitingApplication
server.port = 8080
spring.cloud.gateway.discovery.locator.enabled = true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.main.web-application-type=reactive
spring.redis.timeout=2000

rate-limiter.capacity=10
#adding 5 tokens back into the bucket every second
rate-limiter.refill-rate=5

#The actual microservice your proxy is forwarding allowed requests to.
rate-limiter.api-server-url=http://localhost:8081
rate-limiter.timeout=5000